# Service name
service: bp-cron

# Provider
provider:
  name: aws
  runtime: python3.7
  region: ${env:AWS_DEFAULT_REGION}

# Package
package:
  individually: true
  include:
    - src/**
  exclude:
    - env/**
    - .git/
    - .gitignore
    - node_modules/**
    - README.md
    - package.json
    - package-lock.json
    - Makefile
    - LICENSE
    - ChangeLog.txt

# Lambda functions
functions:
  birthday:
    handler: src/handler/birthday.job
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/1 * * * ? *)

  meeting_reminder:
    handler: src/handler/meeting_reminder.job
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/1 * * * ? *)

  remote_reminder:
    handler: src/handler/remote_reminder.job
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/1 * * * ? *)

# Plugins
plugins:
  - serverless-python-requirements

# Custom settings
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true


# lambda
timeout: 60
