# Service name
service: bp-cron

# Provider
provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  logRetentionInDays: 14
  environment:
    TZ: Asia/Tokyo
  deploymentBucket:
    name: bp-cron-serverless-deployment

# Package
package:
  individually: true
  include:
    - src/**
  exclude:
    - env/**
    - .git/
    - .gitignore
    - .env
    - node_modules/**
    - env.sample
    - README.md
    - package.json
    - package-lock.json
    - Makefile
    - LICENSE
    - ChangeLog.txt
    - requirements.txt
    - black/pyproject.toml
    - tox.ini
    - test/**
    - doc/**

# Lambda functions
functions:
  # 誕生日通知
  # https://tracery.jp/s/f4c338a716074e17bbb242a696de006c
  birthday:
    handler: src/handlers/birthday.job
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(30 00 * * ? *)

  # 9:00 くらいにカレンダーからミーティング一覧通知
  # https://tracery.jp/s/08a63d6bcaba4e7388af40de3dc4453c
  meeting_reminder:
    handler: src/handlers/meeting_reminder.job
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0 00 * * ? *)

  # 直近開催のミーティングを通知
  # https://tracery.jp/s/f34f8f8f368b4c3c9ef5726375e08c22
  meeting_reminder_recent:
    handler: src/handlers/meeting_reminder.recent
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - schedule: cron(0/15 9-23 * * ? *)

# Plugins
plugins:
  - serverless-python-requirements
  - serverless-prune-plugin

# Custom settings
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    layer: true
  prune:
    automatic: true
    number: 3

# lambda
timeout: 60
