version: 2
jobs:
  test-job:
    working_directory: ~/bp-cron
    docker:
    - image: circleci/python:3.7.0-node
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: |
          python3 -m venv venv
          source ./venv/bin/activate
          pip install -U pip setuptools tox
    - run:
        name: Run test
        command: |
          source ./venv/bin/activate
          tox -epy37,flake8
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - store_test_results:
        path: test-results
  deploy-job:
    working_directory: ~/bp-cron
    docker:
    - image: circleci/python:3.7.0-node
    steps:
    - checkout
    - run:
        name: Node.js and npm upgrade
        command: |
          curl -sSL "https://nodejs.org/dist/v12.16.0/node-v12.16.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v12.16.0-linux-x64/bin/node
          curl https://www.npmjs.com/install.sh | sudo bash
    - run:
        name: check node version
        command: node -v
    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    # install Serverless Framework
    - run:
        command: npm install
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - deploy:
        name: Deploy by Serverless Framework
        command: |
          npx sls config credentials -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -p aws
          npx sls deploy
workflows:
  test-and-deploy:
    jobs:
    - test-job
    - deploy-job:
        filters:
          branches:
            only:
            - master
        requires:
        - test-job
  version: 2
